# Copy this file into /etc/systemd/resolved.conf.d/
# Stow will not work as system services cannot traverse through user's home directory by default
[Resolve]
DNS=9.9.9.9#dns.quad9.net 149.112.112.112#dns.quad9.net
DNS=2620:fe::fe#dns.quad9.net 2620:fe::9#dns.quad9.net
DNSOverTLS=yes
Domains=~.
